### ISSUE TITLE
So how do us idiots install this for testing?

### ISSUE THREAD

**Issue by l8gravely** [muradm/ansible-linode-cloud#1]
It would be nice if the readme told me how to install the collection to use it.  I'm a newbie with collections.

**Comment by l8gravely** [comment]
ansible-galaxy collection install https://github.com/muradm/ansible-linode-cloud.git

Bombs out:

Process install dependency map
ERROR! Collection artifact at '/home/mr/.ansible/tmp/ansible-local-22476351zc5qynt/tmp_c7i3apx/ansible-linode-cloud7jpw8o_3.git' is not a valid tar file.

**Comment by muradm** [comment]
It works as any standard collection out there. You may look at collection page: https://galaxy.ansible.com/muradm/linode which gives you straight forward command:
```
$ ansible-galaxy collection install muradm.linode
```
Also you have to better first explore ansible it self. Here is [Using Collections](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html). If you want to install directly from git, there is a [section](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-a-collection-from-a-git-repository).
